blogex:
  token:
    validate:
      time: 86400
  admin:
    permissionList:
      - /auth/login
      - /verify/sliderCode
      - /verify/imageCode
      - /v2/api-docs/**
      - /favicon.ico
      - /auth/logout
      - /swagger-resources/**
      - /webjars/**
      - /doc.html/**
      - /*/*/openApi/**
      - /**/v2/api-docs
      - /uploads/uploadsFile/**
      - /uploads/blogex-ui/**
      - /sitemap_index/**

