blogex:
  swagger:
    show: @blogex.swagger.show@
  mail:
    username: @spring.mail.username@
    password: @spring.mail.password@
    host: @spring.mail.host@
    port: @spring.mail.port@
    visitor:
      reply: @blogex.mail.visitor.reply@
    send:
      admin: @blogex.mail.send.admin@
