blogex:
  token:
    validate:
      time: 86400
  admin:
    role: @blogex.admin.role@
    userName: @blogex.admin.userName@ #你的博客管理员账号
    passWord: @blogex.admin.passWord@ #你的博客管理员密码
    permissionList:
      - /auth/login
      - /verify/sliderCode
      - /verify/imageCode
      - /v2/api-docs/**
      - /favicon.ico
      - /auth/logout
      - /swagger-resources/**
      - /webjars/**
      - /doc.html/**
      - /*/*/openApi/**
      - /**/v2/api-docs
      - /uploads/uploadsFile/**
      - /uploads/blogex-ui/**

