server:
  port: 20010
spring:
  redis:
    database: @spring.redis.database@
    port: @spring.redis.port@
#    password: @spring.redis.password@
    host: @spring.redis.host@
    timeout: @spring.redis.timeout@
  profiles:
    include: blogadmin
  datasource:
    url: @spring.datasource.blogex.url@
    username: @spring.datasource.blogex.username@
    password: @spring.datasource.blogex.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      globalcors:
        # gateway 跨域设置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: # 允许的跨域ajax的请求方式
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: api-routes
          uri: lb://blogex-api
          predicates:
            - Path=/api/**
        - id: upload-routes
          uri: lb://blogex-upload
          predicates:
            - Path=/uploads/**