server:
  port: 26420
blogex:
  swagger:
    show: @blogex.swagger.show@
qiniu:
  enable: @qiniu.enable@
  access-key: @qiniu.accessKey@
  secret-key: @qiniu.secretKey@
  bucket: @qiniu.bucket@
  domain-of-bucket: @qiniu.domain-of-bucket@
spring:
  redis:
    database: @spring.redis.database@
    port: @spring.redis.port@
    #    password: @spring.redis.password@
    host: @spring.redis.host@
    timeout: @spring.redis.timeout@
  webflux:
    base-path: /uploads
  datasource:
    url: @spring.datasource.blogex.url@
    username: @spring.datasource.blogex.username@
    password: @spring.datasource.blogex.password@
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB